server:
  port: 9000


spring:


  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true # DDL ??
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://lifolio.c4gqu0n0yzjg.ap-northeast-2.rds.amazonaws.com:3306/lifolio_schema
    username: admin
    password: lifolio1226

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  header: Authorization
  #umc-3rd-team-project-lifolio-umc-3rd-team-project-lifolio-umc-3rd-team-project-lifolio-umc-3rd-team-project-lifolio
  secret: dW1jLTNyZC10ZWFtLXByb2plY3QtbGlmb2xpby11bWMtM3JkLXRlYW0tcHJvamVjdC1saWZvbGlvLXVtYy0zcmQtdGVhbS1wcm9qZWN0LWxpZm9saW8tdW1jLTNyZC10ZWFtLXByb2plY3QtbGlmb2xpbwo=
  token-validity-in-seconds: 86400

logging:
  level:
    study.cherry: DEBUG

coolsms:
  key: NCSNMZXJWB2W7OSP
  secret: AQA4ROR9GMGDQGKN67CLPAWYKCKPY1SR