server:
  port: 9000


spring:


  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true # DDL ??

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://lifolio.c4gqu0n0yzjg.ap-northeast-2.rds.amazonaws.com:3306/lifolio_schema
    username: admin
    password: lifolio1226

jwt:
  header: Authorization
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  # TODO secret
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

logging:
  level:
    study.cherry: DEBUG
